# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  python_package:  # id of input
    description: 'Python package to be built'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - nuitka3 --python-flag=no_site --python-flag=no_warnings --show-progress --standalone --follow-imports ${{ inputs.python_package }}